name: Python application

on:
  push:
    branches: [ main ] 
  schedule: 
    - cron: '1 */6 * * 1-5'
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip selenium requests bs4

      - name: Execute Python script 
        run: |
          python Main.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated 3hrly_kenyanstocks_prices.json file"
          git push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
